kind: Deployment
apiVersion: Apps/v1
metadata:
  name: nginx-deployment
  namespace: nginx
spec:
  replica: 2
  selector:
    matchLables:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx

    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80

