kind: Service
apiVersion: v1
metadata:
  name: react-app-service
  namespace: react-app
spec:
  selector:
    app: react-app
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: ClusterIP
